# Generated by Django 6.0.2 on 2026-07-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0002_alter_establecimiento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='categoria',
            field=models.CharField(choices=[('banner', 'Banner'), ('oferta', 'Oferta')], default='banner', max_length=10),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='descuento',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
