# Generated by Django 6.0.2 on 2026-07-24 23:46

from django.db import migrations, models


def aprobar_anuncios_existentes(apps, schema_editor):
    """Los anuncios que ya existian antes de este flujo de validacion
    deben seguir siendo visibles al publico, asi que se marcan como
    'aprobado' en lugar de quedar en 'pendiente' (default del campo)."""
    Anuncio = apps.get_model('TuTallerApp', 'Anuncio')
    Anuncio.objects.update(estado='aprobado')


def revertir_aprobacion(apps, schema_editor):
    # No-op: no hay forma de saber cual era el estado original.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0003_anuncio_categoria_anuncio_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='es_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(aprobar_anuncios_existentes, revertir_aprobacion),
    ]
