# Generated by Django 6.1 on 2026-08-22 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0004_anuncio_actualizado_en_anuncio_es_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificacion'), ('verificado', 'Verificado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('numero_nequi', models.CharField(default='+57 315 123 4567', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('admin_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL)),
                ('anuncio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_pendiente', to='TuTallerApp.anuncio')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
