# Generated by Django 6.1 on 2026-08-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0005_pagopendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='TuTallerApp.servicio'),
        ),
    ]
