# Generated by Django 6.1 on 2026-08-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0007_cita_anuncio_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicaciones', models.JSONField(default=list)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ubicaciones'],
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ubicaciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
