# Generated by Django 6.1 on 2026-08-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0009_ubicaciones_y_tarifas_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifaanuncio',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
