# Generated by Django 6.1 on 2026-08-25 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuTallerApp', '0010_tarifaanuncio_duracion_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('web', 'Web'), ('ios', 'iOS')], default='android', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
